import type { Metadata } from "next"
import { Outfit } from "next/font/google"

import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner"

import "./globals.css"

import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server"

import { ConvexClientProvider } from "@/components/convex-client-provider"
import { Modals } from "@/components/modals"
import TanstackProvider from "@/components/tanstack-provider"

const font = Outfit({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${font.className} antialiased`}>
          <ConvexClientProvider>
            <TanstackProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <Modals />
                {children}
                <Toaster richColors position="bottom-right" />
              </ThemeProvider>
            </TanstackProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  )
}
