import type { Metadata } from "next"
import { Outfit } from "next/font/google"

import { Toaster } from "@/components/ui/sonner"

import { ThemeProvider } from "@/components/theme-provider"

import "./globals.css"

import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server"

import { ConvexClientProvider } from "@/components/convex-client-provider"
import TanstackProvider from "@/components/tanstack-provider"

const font = Outfit({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${font.className} antialiased`}>
          <ConvexClientProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <TanstackProvider>{children}</TanstackProvider>
              <Toaster richColors position="bottom-right" />
            </ThemeProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  )
}
