import type { Metadata } from "next"
import { Outfit } from "next/font/google"

import { ThemeProvider } from "@/components/theme-provider"

import "./globals.css"

import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server"

import { NuqsAdapter } from "nuqs/adapters/next/app"

import { ConvexClientProvider } from "@/components/convex-client-provider"

const font = Outfit({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${font.className} antialiased`}>
          <ConvexClientProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <NuqsAdapter>{children}</NuqsAdapter>
            </ThemeProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  )
}
